# Generated by Django 5.2 on 2025-04-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
