# Generated by Django 5.2 on 2025-04-30 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavetype_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='is_paid',
        ),
    ]
