# Generated by Django 5.2 on 2025-04-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('approver', 'Approver'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
